version: '3'

networks:
    default:
        external:
            name: ${SITE_NETWORK}

volumes:
    cfx509certstores:
        external:
            name: ${SITE}_cfx509certstores
    cfappdata:
        external:
            name: ${SITE}_cfappdata

services:
    assembly:
        image: ${CFSTATION_CONTAINER}
        restart: always
        container_name: ${ASSEMBLY_HOSTNAME}
        hostname: ${ASSEMBLY_HOSTNAME}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        ports:
            - "${ASSEMBLY_PORT}"
        command: --ll debug --lf /d/${SITE}-${PRODUCTIONLINE}-assembly.log --pn ${ASSEMBLY_PORT} ${ASSEMBLY_GENERATEALERTS}  ${ASSEMBLY_CYCLETIME} ${ASSEMBLY_POWERCONSUMPTION} --tp /d/trusted --rp /d/rejected --ip /d/issuer --to
            
    test:
        image: ${CFSTATION_CONTAINER}
        restart: always
        container_name: ${TEST_HOSTNAME}
        hostname: ${TEST_HOSTNAME}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        ports:
            - "${TEST_PORT}"
        command: --ll debug --lf /d/${SITE}-${PRODUCTIONLINE}-test.log --pn ${TEST_PORT} ${TEST_GENERATEALERTS}  ${TEST_CYCLETIME} ${TEST_POWERCONSUMPTION} --tp /d/trusted --rp /d/rejected --ip /d/issuer --to
            
    packaging:
        image: ${CFSTATION_CONTAINER}
        restart: always
        container_name: ${PACKAGING_HOSTNAME}
        hostname: ${PACKAGING_HOSTNAME}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        ports:
            - "${PACKAGING_PORT}"
        command: --ll debug --lf /d/${SITE}-${PRODUCTIONLINE}-packaging.log --pn ${PACKAGING_PORT} ${PACKAGING_GENERATEALERTS}  ${PACKAGING_CYCLETIME} ${PACKAGING_POWERCONSUMPTION} --tp /d/trusted --rp /d/rejected --ip /d/issuer --to

    mes:
        image: ${CFMES_CONTAINER}
        restart: always
        container_name: ${MES_HOSTNAME}
        hostname: ${MES_HOSTNAME}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        command: --ll debug --lf /d/${SITE}-${PRODUCTIONLINE}-mes.log --as ${ASSEMBLY_ENDPOINT} --ts ${TEST_ENDPOINT} --ps ${PACKAGING_ENDPOINT} --tp /d/trusted --rp /d/rejected --ip /d/issuer --to