version: '3'

volumes:
    cfx509certstores:
        external:
            name: ${DOMAIN}_cfx509certstores
    cfappdata:
        external:
            name: ${DOMAIN}_cfappdata

services:
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: "no"
        container_name: prx-${DOMAIN}
        hostname: prx-${DOMAIN}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        command: --domain ${DOMAIN} -c "${IOTHUB_CONNECTIONSTRING}" -i -l /d/${DOMAIN}-prx.log -D /d/prx-${DOMAIN}-cs.db

