version: '3'

volumes:
    cfx509certstores:
        external:
            name: ${DOMAIN}_cfx509certstores
    cfappdata:
        external:
            name: ${DOMAIN}_cfappdata

services:
    publisher:
        image: ${OPCPUBLISHER_CONTAINER}
        restart: "no"
        container_name: pub-${DOMAIN}
        hostname: pub-${DOMAIN}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        expose:
            - "62222"
        command: pub-${DOMAIN} -c "${IOTHUB_CONNECTIONSTRING}" -i --lf /d/${DOMAIN}-pub.log --domain ${DOMAIN} --di=60 --tp /d/trusted --rp /d/rejected --ip /d/issuer --to
           
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: "no"
        container_name: prx-${DOMAIN}
        hostname: prx-${DOMAIN}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        command: --domain ${DOMAIN} -c "${IOTHUB_CONNECTIONSTRING}" -i -l /d/${DOMAIN}-prx.log -D /d/prx-${DOMAIN}-cs.db

