version: '2'

volumes:
    cfx509certstores:
        external:
            name: ${DOMAIN}_cfx509certstores
    cfappdata:
        external:
            name: ${DOMAIN}_cfappdata

services:
    publisher:
        image: ${OPCPUBLISHER_CONTAINER}
        restart: "no"
        container_name: publisher-${DOMAIN}
        hostname: publisher-${DOMAIN}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${HOSTDIR}:/docker"
        expose:
            - "62222"
        command: publisher-${DOMAIN} -c "${IOTHUB_CONNECTIONSTRING}" -i --pf /docker/publishednodes-${DOMAIN}.json --lf /docker/${DOMAIN}-publisher.log --domain ${DOMAIN} --di=60 --tp /docker/trusted --rp /docker/rejected --ip /docker/trusted --to
           
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: "no"
        container_name: proxy-${DOMAIN}
        hostname: proxy-${DOMAIN}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${HOSTDIR}:/docker"
        command: -w --domain ${DOMAIN} -c "${IOTHUB_CONNECTIONSTRING}" -i -l /docker/${DOMAIN}-proxy.log -D /docker/proxy-${DOMAIN}-cs.db

volumes:
    cfx509certstores:
    cfappdata: