version: '3'

volumes:
    cfx509certstores:
        external:
            name: ${SITE}_cfx509certstores
    cfappdata:
        external:
            name: ${SITE}_cfappdata

services:
    publisher:
        image: ${OPCPUBLISHER_CONTAINER}
        restart: "no"
        container_name: pub-${SITE}
        hostname: pub-${SITE}
        volumes:
            - "cfx509certstores:/root/.dotnet/corefx/cryptography/x509stores"
            - "${BINDSOURCE}:/d"
        ports:
            - "62222"
        command: pub-${SITE} --dc "${IOTCENTRAL_CONNECTIONSTRING}" -i --lf /d/${SITE}-pub.log --site ${SITE} --di=60 --tp /d/trusted --rp /d/rejected --ip /d/issuer --to --ic --aa
           
