version: '3'

volumes:
    cfappdata:
        external:
            name: ${SITE}_cfappdata

services:
    publisher:
        image: ${OPCPUBLISHER_CONTAINER}
        restart: "no"
        container_name: pub-${SITE}
        hostname: pub-${SITE}
        volumes:
            - "${BINDSOURCE}:/d"
        ports:
            - "62222"
        command: pub-${SITE} -c "${IOTHUB_CONNECTIONSTRING}" -i --lf /d/${SITE}-pub.log --site ${SITE} --di=60 --tp /d/trusted --rp /d/rejected --ip /d/issuer --to --aa
           
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: "no"
        container_name: prx-${SITE}
        hostname: prx-${SITE}
        volumes:
            - "${BINDSOURCE}:/d"
        command: --site ${SITE} -c "${IOTHUB_CONNECTIONSTRING}" -i -l /d/${SITE}-prx.log -D /d/prx-${SITE}-cs.db

