version: '3'

volumes:
    cfappdata:
        external:
            name: ${SITE}_cfappdata

services:
    publisher:
        image: ${OPCPUBLISHER_CONTAINER}
        restart: always
        container_name: pub-${SITE}
        hostname: pub-${SITE}
        extra_hosts:
            ${EXTRAHOSTS}
        volumes:
            - "${BINDSOURCE}:/d"
        expose:
            - "62222"
        ports:
            - "62222:62222"
        command: pub-${SITE} --pf /d/pn-${SITE}.json ${TELEMETRYCONFIG_OPTION} --lf /d/${SITE}-pub.log --site ${SITE} --di=60 --tp /d/trusted --rp /d/rejected --ip /d/issuer --to --aa
           
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: always
        container_name: prx-${SITE}
        hostname: prx-${SITE}
        extra_hosts:
            ${EXTRAHOSTS}
        volumes:
            - "${BINDSOURCE}:/d"
        command: -l /d/${SITE}-prx.log -c "${IOTHUB_CONNECTIONSTRING}" -D /d/prx-${SITE}-cs.db --domain ${SITE} 

    twin:
        image: ${OPCTWIN_CONTAINER}
        restart: always
        container_name: twin-${SITE}
        hostname: twin-${SITE}

    plc:
        image: ${OPCPLC_CONTAINER}
        restart: always
        container_name: plc-${SITE}
        hostname: plc-${SITE}
        volumes:
            - "${BINDSOURCE}:/d"
        expose:
            - "50000"
        ports:
            - "50000:50000"
        command: --tp /d/trusted --rp /d/rejected --ip /d/issuer --to --aa
           

