version: '3'

volumes:
    cfappdata:
        external:
            name: ${SITE}_cfappdata

services:
    proxy:
        image: ${OPCPROXY_CONTAINER}
        restart: "no"
        container_name: prx-${SITE}-init
        hostname: prx-${SITE}
        volumes:
            - "${BINDSOURCE}:/d"
        command: --domain ${SITE} -c "${IOTHUB_CONNECTIONSTRING}" -i -l /d/${SITE}-prx.log -D /d/prx-${SITE}-cs.db

